---

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_certname }}/cert.pem
  register: letsencrypt_cert

- name: Issue pre_hook command if configured
  become: true
  command: "{{ certbot_pre_hook }}"
  when: certbot_pre_hook is defined
  ignore_errors: yes

- name: Generate new certificate if one doesn't exist.
  become: true
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists and not certbot_skip_generation

- name: Invoke deploy-hook to provision generated certificates  # noqa 305
  become: true
  shell: >-
    RENEWED_DOMAINS={{ cert_item.domains | join(' ') | quote }}
    RENEWED_LINEAGE={{ cert_lineage | quote }}
    /etc/letsencrypt/renewal-hooks/deploy/deploy_hook.sh
  when: not letsencrypt_cert.stat.exists and not certbot_skip_generation
  loop: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert_item
