---

- name: Ensure /etc/letsencrypt folders exists
  become: true
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    recurse: true

- name: Deploy-hook
  become: true
  template:
    dest: /etc/letsencrypt/renewal-hooks/deploy/deploy_hook.sh
    src: deploy_hook.sh.j2
    mode: 0774
