---

- name: Ensure /etc/letsencrypt folders exists
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: true
  loop:
    - {path: "/etc/letsencrypt/renewal-hooks/deploy"}
    - {path: "/etc/letsencrypt/renewal-hooks/pre"}

- name: Deploy-hook
  become: true
  template:
    dest: /etc/letsencrypt/renewal-hooks/deploy/deploy_hook.sh
    src: deploy_hook.sh.j2
    mode: 0774

- name: Pre-hook
  become: true
  template:
    dest: /etc/letsencrypt/renewal-hooks/pre/pre_hook.sh
    src: pre_hook.sh.j2
    mode: 0774
