---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- name: Load standalone mode variables
  include_vars: 
    file: standalone.yml
  when: certbot_create_method == "standalone"

- name: Load standalone mode variables
  include_vars: 
    file: standalone_port.yml
  when: certbot_create_method == "standalone_port"

- name: Load webroot mode variables
  include_vars: 
    file: webroot.yml
  when: certbot_create_method == "webroot"
