---
- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  when: ansible_os_family != 'RedHat'

- name: Enable systemd renewal
  systemd:
    name: certbot-renew.timer
    enabled: yes
    state: started
  when: ansible_os_family == 'RedHat'
