---
- name: Add cron job for certbot renewal (if configured).
  become: true
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  when: ansible_os_family != 'RedHat'

- name: Enable systemd renewal
  become: true
  systemd:
    name: certbot-renew.timer
    enabled: yes
    state: started
  when: ansible_os_family == 'RedHat'

- name: Modify certbot config for renewals options
  become: true
  replace:
    dest: "/etc/sysconfig/certbot"
    regexp: "^CERTBOT_ARGS=.*"
    replace: "CERTBOT_ARGS=\"{{ certbot_auto_renew_options }}\""
  when: ansible_os_family == "RedHat"

